apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          {{- with .Values.deployment }}
          image: {{ .image }}:{{ .tag }}
          ports:
            - containerPort: {{ .containerPort | default 80 }}
          {{- end }}
          env:
            {{- range .Values.deployment.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}